"""
Custom Reporting Tool
Security Phase - Step 2A: Secret Encryption / Key Management

This module provides the cryptographic foundation for protecting
saved database credentials.

Step 2A intentionally does NOT modify the existing connection registry.
Existing plaintext credentials remain untouched until Step 2B.

Key material is recovered or generated by key_manager, so this module does not require a project-local .env file.
"""

from __future__ import annotations

import os
from typing import Any

from cryptography.fernet import Fernet, InvalidToken

from key_manager import ensure_keys, get_key, get_previous_key


ensure_keys()


class SecretConfigurationError(RuntimeError):
    """Raised when the encryption key is missing or invalid."""


class SecretDecryptionError(RuntimeError):
    """Raised when an encrypted secret cannot be decrypted."""


def _get_encryption_key() -> bytes:
    """Read and validate the configured Fernet key."""
    try:
        return get_key("ENCRYPTION_KEY").encode("utf-8")
    except (RuntimeError, ValueError) as exc:
        raise SecretConfigurationError(
            "ENCRYPTION_KEY is not available from the persistent key lifecycle."
        ) from exc


def _get_previous_encryption_key() -> bytes | None:
    key = get_previous_key("ENCRYPTION_KEY_PREVIOUS")
    return key.encode("utf-8") if key else None


def get_previous_fernet() -> Fernet | None:
    key = _get_previous_encryption_key()
    if not key:
        return None
    try:
        return Fernet(key)
    except (ValueError, TypeError) as exc:
        raise SecretConfigurationError("ENCRYPTION_KEY_PREVIOUS is invalid.") from exc


def get_fernet() -> Fernet:
    """Return the configured Fernet cipher."""
    try:
        return Fernet(_get_encryption_key())
    except (ValueError, TypeError) as exc:
        raise SecretConfigurationError(
            "ENCRYPTION_KEY is invalid. "
            "Generate a valid Fernet key and configure it in .env."
        ) from exc


def generate_encryption_key() -> str:
    """
    Generate a new Fernet key.

    Generate once and store the resulting value securely.
    Do not regenerate the key after real credentials have been encrypted.
    """
    return Fernet.generate_key().decode("utf-8")


def encrypt_secret(value: Any) -> str | None:
    """Encrypt a non-empty secret value."""
    if value is None:
        return None

    text = str(value)

    if text == "":
        return None

    return get_fernet().encrypt(
        text.encode("utf-8")
    ).decode("utf-8")


def decrypt_secret(token: str | None) -> str | None:
    """Decrypt an encrypted Fernet token."""
    if token is None or token == "":
        return None

    encrypted = token.encode("utf-8")
    try:
        return get_fernet().decrypt(encrypted).decode("utf-8")
    except (InvalidToken, UnicodeDecodeError, ValueError, TypeError) as active_error:
        previous = get_previous_fernet()
        if previous is not None:
            try:
                return previous.decrypt(encrypted).decode("utf-8")
            except (InvalidToken, UnicodeDecodeError, ValueError, TypeError):
                pass
        raise SecretDecryptionError(
            "Unable to decrypt stored secret. "
            "The configured encryption key may be incorrect or the stored value "
            "may not be a valid encrypted secret."
        ) from active_error


def is_encrypted_secret(value: Any) -> bool:
    """
    Detect the normal Fernet token format.

    This checks format only; it does not prove that the current key
    can decrypt the value.
    """
    return isinstance(value, str) and value.startswith("gAAAAA")


def mask_secret(value: Any, visible_chars: int = 0) -> str | None:
    """Return a safe masked representation for diagnostics."""
    if value is None:
        return None

    text = str(value)

    if not text:
        return ""

    if visible_chars <= 0:
        return "********"

    visible_chars = min(visible_chars, len(text))

    return (
        text[:visible_chars]
        + "*" * max(len(text) - visible_chars, 0)
    )
