"""
Custom Reporting Tool
Security Phase - Step 3B: User Registry

Local JSON-backed user registry for the authentication layer.

IMPORTANT:
- Passwords are never stored in plaintext.
- Password hashes are generated by auth.hash_password().
- Public user objects never contain password hashes.
- This registry does not modify existing reporting data.
"""

from __future__ import annotations

from datetime import datetime, timezone
from pathlib import Path
from typing import Any
import secrets

from auth import hash_password, safe_user, verify_password
from permissions import DEFAULT_REPORT_USER_PERMISSIONS, normalize_permissions
from metadata_repository import create_metadata_repository
from config import METADATA_DB_FILE


from config import DATA_DIR

BASE_DIR = Path(__file__).resolve().parent
USERS_FILE = DATA_DIR / "users.json"
METADATA_REPOSITORY = create_metadata_repository(USERS_FILE, collection="users", db_path=METADATA_DB_FILE)


def _ensure_file() -> None:
    METADATA_REPOSITORY.ensure()


def _read() -> list[dict[str, Any]]:
    return METADATA_REPOSITORY.read()


def _write(users: list[dict[str, Any]]) -> None:
    METADATA_REPOSITORY.write(users)


def get_user_by_id(user_id: str) -> dict[str, Any] | None:
    for user in _read():
        if user.get("id") == user_id:
            return user
    return None


def get_user_by_username(username: str) -> dict[str, Any] | None:
    normalized = str(username).strip().lower()

    for user in _read():
        if str(user.get("username", "")).strip().lower() == normalized:
            return user

    return None


def list_users() -> list[dict[str, Any]]:
    """Return safe user objects without password hashes."""
    return [safe_user(user) for user in _read()]


def create_user(
    username: str,
    password: str,
    role: str = "report_user",
    permissions: list[str] | None = None,
) -> dict[str, Any]:
    username = str(username).strip()

    if len(username) < 3 or len(username) > 100:
        raise ValueError("Username must contain 3 to 100 characters.")

    if get_user_by_username(username):
        raise ValueError("Username already exists.")

    if not isinstance(password, str) or len(password) < 8:
        raise ValueError("Password must contain at least 8 characters.")

    if len(password) > 1024:
        raise ValueError("Password is too long.")

    allowed_roles = {"admin", "report_user", "custom"}

    if role not in allowed_roles:
        raise ValueError("Invalid user role.")

    if role == "admin":
        assigned_permissions = None
    elif permissions is None:
        assigned_permissions = sorted(DEFAULT_REPORT_USER_PERMISSIONS) if role == "report_user" else []
    else:
        assigned_permissions = normalize_permissions(permissions)

    now = datetime.now(timezone.utc).isoformat()

    user = {
        "id": f"user_{secrets.token_hex(8)}",
        "username": username,
        "password_hash": hash_password(password),
        "role": role,
        "permissions": assigned_permissions,
        "active": True,
        "created_at": now,
        "updated_at": now,
    }

    users = _read()
    users.append(user)
    _write(users)

    return safe_user(user)


def update_user(
    user_id: str,
    *,
    role: str | None = None,
    permissions: list[str] | None = None,
    password: str | None = None,
    active: bool | None = None,
) -> dict[str, Any] | None:
    users = _read()
    allowed_roles = {"admin", "report_user", "custom"}

    for index, user in enumerate(users):
        if user.get("id") != user_id:
            continue

        updated = dict(user)

        if role is not None:
            role = str(role).strip()
            if role not in allowed_roles:
                raise ValueError("Invalid user role.")
            updated["role"] = role

        effective_role = updated.get("role", "report_user")

        if effective_role == "admin":
            updated["permissions"] = None
        elif permissions is not None:
            updated["permissions"] = normalize_permissions(permissions)
        elif "permissions" not in updated:
            updated["permissions"] = sorted(DEFAULT_REPORT_USER_PERMISSIONS)

        if password is not None:
            if not isinstance(password, str) or len(password) < 8:
                raise ValueError("Password must contain at least 8 characters.")
            if len(password) > 1024:
                raise ValueError("Password is too long.")
            updated["password_hash"] = hash_password(password)

        if active is not None:
            updated["active"] = bool(active)

        updated["updated_at"] = datetime.now(timezone.utc).isoformat()
        users[index] = updated
        _write(users)
        return safe_user(updated)

    return None


def delete_user(user_id: str) -> bool:
    users = _read()
    updated = [user for user in users if user.get("id") != user_id]

    if len(updated) == len(users):
        return False

    _write(updated)
    return True


def authenticate_user(
    username: str,
    password: str,
) -> dict[str, Any] | None:
    """
    Authenticate a user without exposing its password hash.
    """
    user = get_user_by_username(username)

    if not user:
        return None

    if not bool(user.get("active", True)):
        return None

    stored_hash = user.get("password_hash")

    if not isinstance(stored_hash, str):
        return None

    if not verify_password(password, stored_hash):
        return None

    return user


def set_user_active(
    user_id: str,
    active: bool,
) -> dict[str, Any] | None:
    users = _read()

    for index, user in enumerate(users):
        if user.get("id") != user_id:
            continue

        updated = dict(user)
        updated["active"] = bool(active)
        updated["updated_at"] = datetime.now(timezone.utc).isoformat()

        users[index] = updated
        _write(users)

        return safe_user(updated)

    return None
